/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AInput: typeof import('./components/a-input.vue')['default']
    AsideAccount: typeof import('./components/aside-account.vue')['default']
    AsideCategory: typeof import('./components/aside-category.vue')['default']
    AsideOther: typeof import('./components/aside-other.vue')['default']
    AsideTrending: typeof import('./components/aside-trending.vue')['default']
    BackendMenu: typeof import('./components/backend-menu.vue')['default']
    BackTop: typeof import('./components/back-top.vue')['default']
    BgPlum: typeof import('./components/bg-plum.vue')['default']
    ClientOnly: typeof import('./components/client-only.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    FrontendComment: typeof import('./components/frontend-comment.vue')['default']
    GlobalNavigation: typeof import('./components/global-navigation.vue')['default']
    ItemActions: typeof import('./components/item-actions.vue')['default']
    MessageComp: typeof import('./components/messageComp.vue')['default']
    ReloadPrompt: typeof import('./components/reload-prompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignIn: typeof import('./components/sign-in.vue')['default']
    SignUp: typeof import('./components/sign-up.vue')['default']
    TopicsItem: typeof import('./components/topics-item.vue')['default']
    TopicsItemNone: typeof import('./components/topics-item-none.vue')['default']
  }
}
