/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AInput: typeof import('./components/a-input.vue')['default']
    ArticleCard: typeof import('./components/ArticleCard.vue')['default']
    AsideAccount: typeof import('./components/aside-account.vue')['default']
    AsideCategory: typeof import('./components/aside-category.vue')['default']
    AsideOther: typeof import('./components/aside-other.vue')['default']
    AsideTrending: typeof import('./components/aside-trending.vue')['default']
    AuthModal: typeof import('./components/AuthModal.vue')['default']
    BackendMenu: typeof import('./components/backend-menu.vue')['default']
    BackTop: typeof import('./components/back-top.vue')['default']
    BackToTop: typeof import('./components/BackToTop.vue')['default']
    BaseButton: typeof import('./components/BaseButton.vue')['default']
    BgPlum: typeof import('./components/bg-plum.vue')['default']
    ClientOnly: typeof import('./components/client-only.vue')['default']
    ConfirmDialog: typeof import('./components/ConfirmDialog.vue')['default']
    DeviceConnect: typeof import('./components/elaphure/DeviceConnect.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    EntityCard: typeof import('./components/EntityCard.vue')['default']
    FirmwareUpload: typeof import('./components/elaphure/FirmwareUpload.vue')['default']
    FlashConfig: typeof import('./components/elaphure/FlashConfig.vue')['default']
    FrontendComment: typeof import('./components/frontend-comment.vue')['default']
    GlassPanel: typeof import('./components/GlassPanel.vue')['default']
    GlobalNavigation: typeof import('./components/global-navigation.vue')['default']
    ItemActions: typeof import('./components/item-actions.vue')['default']
    MarkdownRenderer: typeof import('./components/MarkdownRenderer.vue')['default']
    MessageComp: typeof import('./components/messageComp.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    ReloadPrompt: typeof import('./components/reload-prompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBox: typeof import('./components/SearchBox.vue')['default']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    SignIn: typeof import('./components/sign-in.vue')['default']
    SignUp: typeof import('./components/sign-up.vue')['default']
    ThemeToggle: typeof import('./components/ThemeToggle.vue')['default']
    Toast: typeof import('./components/Toast.vue')['default']
    TopicsItem: typeof import('./components/topics-item.vue')['default']
    TopicsItemNone: typeof import('./components/topics-item-none.vue')['default']
  }
}
