/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AInput: typeof import('./components/form/a-input.vue')['default']
    AsideCategory: typeof import('./components/aside-category.vue')['default']
    AsideOther: typeof import('./components/aside-other.vue')['default']
    AsideTrending: typeof import('./components/aside-trending.vue')['default']
    BackendMenu: typeof import('./components/backend-menu.vue')['default']
    BackToTop: typeof import('./components/BackToTop.vue')['default']
    BaseButton: typeof import('./components/base/BaseButton.vue')['default']
    BgPlum: typeof import('./components/bg-plum.vue')['default']
    ClientOnly: typeof import('./components/client-only.vue')['default']
    ConfirmDialog: typeof import('./components/ConfirmDialog.vue')['default']
    EntityCard: typeof import('./components/base/EntityCard.vue')['default']
    GlassPanel: typeof import('./components/base/GlassPanel.vue')['default']
    GlobalNavigation: typeof import('./components/layout/global-navigation.vue')['default']
    MessageComp: typeof import('./components/messageComp.vue')['default']
    Navbar: typeof import('./components/layout/Navbar.vue')['default']
    ReloadPrompt: typeof import('./components/reload-prompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBox: typeof import('./components/form/SearchBox.vue')['default']
    Sidebar: typeof import('./components/layout/Sidebar.vue')['default']
    ThemeToggle: typeof import('./components/ThemeToggle.vue')['default']
    Toast: typeof import('./components/Toast.vue')['default']
    TopicsItem: typeof import('./components/topics-item.vue')['default']
    TopicsItemNone: typeof import('./components/topics-item-none.vue')['default']
  }
}
