import {
    defineConfig,
    presetAttributify,
    presetIcons,
    presetTypography,
    presetUno,
    presetWebFonts,
    transformerDirectives,
    transformerVariantGroup,
} from 'unocss'

export default defineConfig({
    shortcuts: {
        'glass-panel': 'backdrop-filter-blur-16px bg-white/85 border border-silver-400/30 rounded-20px',
        'entity-card': 'bg-surface rounded-20px p-6 shadow-md hover:shadow-xl transition-all',
        'btn-primary': 'bg-primary text-black rounded-16px px-6 py-2.5 font-medium hover:bg-primary-light transition-all',
        'btn-secondary': 'bg-surface-variant text-primary rounded-16px px-6 py-2.5 font-medium hover:bg-gray-200 transition-all',
        'wrap': 'relative mx-auto max-w-[1600px] md:max-w-[1400px] sm:max-w-[1200px] xs:max-w-[1000px] p-0 xs:px-10 sm:px-10',
        'main': 'flex pt-10 pb-10 gap-5 flex-wrap justify-center',
        'main-left': 'flex-1 min-w-[660px] md:min-w-full',
        'main-right': 'flex-none w-[320px] md:flex-1 md:w-[660px] md:m-0',
        'base-input': 'h-11 px-3.5 text-base bg-white border-none rounded-md box-border appearance-none focus:bg-white focus:shadow-[0_0_8px_rgba(0,0,0,0.02)_inset]',
        'card': 'relative block bg-white rounded-md shadow-[0_1px_2px_rgba(0,0,0,0.05)] sm:rounded-0',
        'card-content': 'p-6',
        'card-title': 'text-lg font-normal leading-6 tracking-[0.2em] text-center',
        'card-title-link': 'text-[#B3E5FC] hover:opacity-80',
        'feed': 'p-6',
        'feed-content': 'text-base text-gray-500',
        'feed-source-time': 'flex justify-between',
        'feed-time': 'text-sm',
        'feed-main-link': 'text-lg font-bold leading-[1.32] text-gray-600 hover:opacity-80',
        'feed-article-content': 'block max-h-[125px] overflow-hidden leading-6 text-gray-800',
        'topic-link-item': 'inline-block h-8 px-3 text-sm leading-8 text-white bg-[#1976D2] border-none rounded-full hover:bg-[#1976D2] hover:text-white',
        'question-title': 'text-xl',
        'question-title-link': 'text-[#7a7374] hover:opacity-80',
        'question-content': 'p-6',
        'question-meta': 'inline-block mt-3 text-sm leading-1 text-[#bac1c2]',
        'question-actions': 'border-t border-[#eef2f2] h-12 text-0',
        'answer-content': 'p-6',
        'article-content': 'word-wrap:break-word',
        'trending-item': 'pl-8.5 mt-4.5',
        'trending-title': 'text-base font-bold text-[#3e4545] hover:text-[#7a7374]',
        'trending-meta': 'mt-2',
        'trending-meta-item': 'inline-block text-sm text-[#969f9f]',
        'topic-item': 'relative flex p-5 border-t border-[#eef2f2] hover:trending-title:text-[#7a7374]',
        'avatar-link': 'mr-3 text-0',
        'avatar-image': 'w-12.5 h-12.5 rounded-full',
        'topic-title': 'text-base text-[#3e4545] transition-all duration-200',
        'topic-meta': 'mt-0.5 text-sm text-gray-600',
        'load-more-wrap': 'pt-10 pb-10 text-center',
        'load-more': 'relative inline-block w-25 h-25 text-base font-normal leading-25 tracking-[0.12em] text-[#7a7374] text-center text-indent-[0.12em] border-2 border-[#BBDEFB] rounded-full box-border hover:opacity-80 hover:scale-104',
        'settings-section': 'py-6 border-t border-[#f4f4f4]',
        'settings-section-title': 'text-base',
        'settings-item': 'flex',
        'settings-title': 'text-base font-normal',
        'settings-item-content': 'flex-1 ml-5',
        'list-section': 'flex justify-between py-3 text-sm border-t border-[#f4f4f4]',
        'list-header': 'text-base',
        'list-title': 'flex-1 w-0',
        'list-category': 'flex-none w-[140px]',
        'list-date': 'flex-none w-[140px]',
        'list-action': 'flex-none w-[140px]',
        'list-username': 'w-[120px]',
        'list-email': 'w-[310px]',
        'select-item': 'w-full px-3.5 leading-11 cursor-pointer bg-none border border-[#e2e9e9] rounded-md box-border appearance-none',
        'settings-input-wrap': 'relative block',
        'settings-footer': 'p-6 border-t border-[#f4f4f4] text-right',
        'admin-load-more': 'block text-center',
    },
    theme: {
        colors: {
            primary: {
                DEFAULT: '#A8A8A8',
                light: '#D4D4D4',
                dark: '#787878',
            },
            surface: {
                DEFAULT: '#FAFAFA',
                variant: '#F0F0F0',
                dark: '#1A1A1A',
            },
            background: {
                DEFAULT: '#FFFFFF',
                dark: '#000000',
            },
            text: {
                'primary': '#000000',
                'secondary': '#4A4A4A',
                'hint': '#8A8A8A',
                'dark': '#FFFFFF',
                'secondary-dark': '#B0B0B0',
                'hint-dark': '#707070',
            },
            silver: {
                50: '#FAFAFA',
                100: '#F5F5F5',
                200: '#E5E5E5',
                300: '#D4D4D4',
                400: '#A8A8A8',
                500: '#8B8B8B',
                600: '#787878',
                700: '#5C5C5C',
                800: '#3C3C3C',
                900: '#1A1A1A',
            },
        },
        breakpoints: {
            'xs': '480px',
            'sm': '640px',
            'md': '768px',
            'lg': '1024px',
            'xl': '1280px',
            '2xl': '1536px',
        },
        animation: {
            'circle-loading': 'circle-loading 1.2s linear infinite',
        },
        keyframes: {
            'circle-loading': {
                '0%': { transform: 'rotate(0)' },
                '100%': { transform: 'rotate(360deg)' },
            },
        },
    },
    presets: [
        presetUno(),
        presetAttributify(),
        presetIcons({
            scale: 1.2,
            cdn: 'https://esm.sh/',
        }),
        presetTypography(),
        presetWebFonts({
            fonts: {
                sans: 'Inter:400,500,600,700',
                mono: 'Fira Code',
            },
        }),
    ],
    transformers: [
        transformerDirectives(),
        transformerVariantGroup(),
    ],
})
